dist: focal

language: minimal
  
before_install:
  - sudo add-apt-repository ppa:neovim-ppa/stable -y
  - sudo apt-get update
  - sudo apt-get -y install neovim

install:
  - git clone https://github.com/leafOfTree/vim-test ../vim-test --depth=1 

script:
  - bash ../test/start.sh project vim-project
